rust_input: [src/api.rs]
dart_output: [../lib/bridge_generated.dart]
# wasm: true
dart_decl_output: ../lib/bridge_definitions.dart
dart_format_line_length: 120
dart_enums_style: true
c_output: [c_output_path/c_output.h]
extra_c_output_path:
  - c_output_path_extra/
no_use_bridge_in_method: true
wasm: true
# dump: []
